/**
 * The plugin's delegation skill: the task-brief template and pre-dispatch checks
 * from the author's own skill, merged with the operational facts of this plugin
 * (tool parameters, background jobs, panel, the live shell channel, timeouts),
 * so one skill answers "how do I delegate here".
 *
 * Registered at runtime with the plugin, so installing the plugin installs it —
 * there is no second copy under the user's skills directory to drift out of sync.
 */
import type { SkillRegistration } from '@deepseek-ai/dsh-skill'

export const DELEGATION_SKILL: SkillRegistration = {
  name: 'claude-code-delegation',
  description:
    '委派 Claude Code 的完整规程：任务书模板 + 开派前置检查 + 回传验收，以及本插件工具（claude_code）的参数、后台作业、实时输出通道与监控面板。要派编码子任务给本机 Claude Code，或用户说"派 Claude 写/改代码"时用它。',
  whenToUse:
    '用户要求写/改代码且任务自包含、边界清晰（尤其"让 Claude 来写/修 XX"）；或维护 dsh-claude-delegate 插件本身时。',
  source: 'runtime' as const,
  content: [
    '# Claude Code 委派规程（任务书 + 前置检查 + 验收）',
    '',
    '> **外包的是「读遍仓库再实现」，不是「定义什么叫做对」。**',
    '',
    '- 读代码 / 定位 / 实现 / 自测 → Claude Code 的活（它写全部实现代码，一行不少）',
    '- 业务规则 / 验收标准 / 接口签名 → 主代理（或用户）的活，**派之前必须先定完**',
    '',
    '委派失败的根因不是"忘了模板"，是"整包送出去感觉更快"。下文带 🔒 的字段是硬约束，不是建议。',
    '',
    '## 一、开派前置检查（三条全过才派）',
    '',
    '任何一条不过 → **不派**，先补。',
    '',
    '1. **验收标准能不能写成具体断言？**',
    '   写不出断言 → 需求本身没成形，派出去只会摩擦。先补测试或决策表。',
    '2. **要不要向它解释「为什么」？**',
    '   要 → 说明你打算用自然语言传业务逻辑。**改**：把「为什么」写成决策表或测试用例。',
    '   🔒 任务书里不写业务背景、不写来龙去脉；领域背景最多一句话。',
    '3. **边界能不能用路径说清？**',
    '   说清"只改哪些目录、禁止改哪些文件" → 可以派。说不清 → 任务太大，拆到能说清为止。',
    '',
    '## 二、任务书（🔒 = 硬约束）',
    '',
    '```markdown',
    '## 目标',
    '<一句话：让哪个测试全绿 / 实现哪个契约>',
    '',
    '## 上下文（🔒 最多 5 条要点；禁止粘贴需求原文、对话历史、业务背景）',
    '- 入口：<路径:行号> <一句话>',
    '- 契约：<路径>（接口签名/类型定义所在文件）',
    '- 参考实现：<路径>（可选，找不到相似的就说没有）',
    '',
    '## 验收标准（🔒 必须可机械判定，至少一条）',
    '- [ ] <测试文件路径> 全绿',
    '- [ ] <具体行为断言>',
    '- 决策表：<无 / 见 <路径>>',
    '',
    '## 技术约束',
    '<仅列可验证项，如"不新增依赖""保持现有导出签名不变">',
    '',
    '## 边界（🔒 必填）',
    '- 允许改：<路径/目录>',
    '- 禁止改：<契约文件>、<测试文件>、<其他目录>',
    '',
    '## 禁令（🔒 逐条照抄）',
    '- 不得 commit / push / 改动 git 状态',
    '- 不得修改测试或契约文件来让实现通过',
    '- 遇到决策表未覆盖的情况，**不得自行推断**，停下并在报告中列出',
    '',
    '## 自测',
    '- 预授权命令白名单：<如 pnpm test -- export>',
    '- 备注：permissionMode=acceptEdits 只放行文件编辑；未预授权 Bash 时命令会被拒，被拒则跳过自测、**不得中断任务**',
    '',
    '## 输出格式',
    '按下方 outputSchema 返回结构化结果；报告全文同时写入 <workspace>\\.claude-runs\\<task-id>\\report.json',
    '',
    '## cwd',
    '<绝对路径，🔒 必须显式传；不传会落到宿主进程 cwd>',
    '```',
    '',
    '## 三、outputSchema 骨架（卡死字段，禁止自由叙述）',
    '',
    '把下面这份 schema 传给 claude_code 的 `outputSchema` 参数，结果会回到 `structuredOutput`：',
    '',
    '```json',
    '{',
    '  "type": "object",',
    '  "additionalProperties": false,',
    '  "required": ["files_changed", "criteria_map", "undefined_cases", "tests_run", "uncertainties"],',
    '  "properties": {',
    '    "files_changed": { "type": "array", "items": { "type": "string" } },',
    '    "criteria_map": {',
    '      "type": "array",',
    '      "items": {',
    '        "type": "object",',
    '        "additionalProperties": false,',
    '        "required": ["criterion", "evidence"],',
    '        "properties": {',
    '          "criterion": { "type": "string" },',
    '          "evidence": { "type": "string" }',
    '        }',
    '      }',
    '    },',
    '    "undefined_cases": { "type": "array", "items": { "type": "string" } },',
    '    "tests_run": {',
    '      "type": "array",',
    '      "items": {',
    '        "type": "object",',
    '        "additionalProperties": false,',
    '        "required": ["cmd", "result"],',
    '        "properties": { "cmd": { "type": "string" }, "result": { "type": "string" } }',
    '      }',
    '    },',
    '    "uncertainties": { "type": "array", "items": { "type": "string" } }',
    '  }',
    '}',
    '```',
    '',
    '🔒 `undefined_cases` 与 `uncertainties` **必填**（无内容也给空数组）。这两栏是逼它主动暴露盲区的探照灯，空数组本身也是有信息的。',
    '',
    '## 四、本插件（dsh-claude-delegate）操作事实',
    '',
    '### 工具与参数',
    '- 工具名 `claude_code`：`task`（🔒 必填，自包含任务书）、`cwd`、`model`、`permissionMode`、`allowedTools`、`maxTurns`、`effort`、`maxThinkingTokens`、`thinkingMode`、`maxBudgetUsd`、`timeoutMs`、`warnTimeoutMs`、`warnIntervalMs`、`appendSystemPrompt`、`outputSchema`、`resume`、`run_in_background`。',
    '- 🔒 **`cwd` 必须显式传绝对路径**：实测不传会落到宿主进程的 cwd（如 C:\\Windows\\system32），**不是**主会话工作目录，会连带加载错误的项目配置。',
    '- `model` 默认跟随主会话模型；别名（sonnet / opus / haiku / fable）由本机 `~/.claude/settings.json` 决定，可能被映射到第三方中转模型——**不得声称产出「来自 Claude」**，准确表述是「以 Claude Code 方式（外壳）运行」。重大派遣前先读一眼该配置文件核实别名。',
    '- `resume` 可用：调用返回的正文末尾带 `session: <id>` 一行，把它作为 `resume` 传回即可让下一轮记住上文；会话已被清理时会报 no conversation found，此时去掉 `resume` 重派。',
    '- 需要它跑命令时必须传 `allowedTools`（如 `["Read","Write","Edit","Bash","Glob","Grep"]`）预授权：`acceptEdits` 只放行文件编辑，未预授权的命令会被拒。',
    '',
    '### 后台作业',
    '- 长任务传 `run_in_background: true`，工具立刻返回 `{ kind: "background", jobId }`，不占用当前这轮。',
    '- 用 `job_output` 增量读实时输出（每次只给上次之后的新内容），`job_list` 看在跑的，`job_kill` 取消；结束时 DSH 会推送完成通知，不需要轮询。',
    '- 文本流里 `[tool] <名字>` 是工具调用标记；会话 id 在结算文本末尾以 `session: <id>` 给出，后台作业照样能 resume。',
    '- 短任务（几十秒内）直接前台调用，前台一次性返回最终文本。',
    '',
    '### 监控面板（Web 端）',
    '- 会话头「Claude Code」标签页：任务列表 + 实时输出（思考块可折叠、工具卡片带参数与结果、运行中显示已运行秒数）+ 取消。',
    '- 面板同时列出 harness 原生 `subagent` 后台作业（kind=subagent）：它们的输出来自 harness 的观察流，取消走它的 kill 通道。人类用户可以自己盯，你不用替他转述实时输出。',
    '',
    '### 超时与告警（两级）',
    '- 硬超时 `timeoutMs`（默认 2h）：到点中止，任务 failed timed out。',
    '- 告警 `warnTimeoutMs`（默认 1h）+ 周期 `warnIntervalMs`（默认 30min）：只标注，不中止。收到告警且无进展时，请用户决策：继续等 / 取消 / 用 resume 缩小范围重派，不要自作主张强杀。',
    '',
    '### 长命令实时输出（mcp__dsh__shell）',
    '- 🔒 预计超过 20 秒的命令（构建、测试、长脚本、批量处理）**用 `mcp__dsh__shell` 执行**，不要用内置 Bash：SDK 从不转发内置 Bash 的 stdout，只有走这条通道用户才看得到逐行实时输出。',
    '- 参数：`command`（必填，按 bash 语法）、`cwd`（可选）、`timeoutMs`（可选，默认 15 分钟，到点杀整棵进程树）、`purpose`（可选，一句话说明，显示在面板的命令行上）。',
    '- 它每次都是**一次性进程**：`cd`/`export` 不跨调用保留；短命令与需要连续 shell 状态的命令继续用内置 Bash。',
    '- 通道输出只进面板、**不进** `job_output`；所以无论跑了什么命令，**结论与关键输出仍必须写在你的回复正文里**（那是唯一可靠的出口）。',
    '',
    '### 面板里还能看到谁',
    '- 面板列出本插件的 `claude-code` 委派，也会把 harness 原生的 `subagent` 后台作业一起列出来（那些作业没有本插件的事件流，走 harness 的观察流渲染），两者的取消通道各自独立。',
    '',
    '## 五、回传后验收（主代理做）',
    '',
    '**一、独立重跑验证（不读实现）**',
    '- 自己执行一遍原始测试命令，**不采信报告里的测试结论**',
    '- `files_changed` 是否越界（超出"允许改"的路径 = 直接打回）',
    '- 契约文件、测试文件有没有被动过 ← **抓"改测试来迁就实现"，这是最典型的作弊**',
    '',
    '以上都能机械完成，**不需要读实现代码**。',
    '',
    '**二、关键接口的语义判断（需要时才做）**',
    '- 有疑问时，只读契约文件与关键签名；🔒 不要试图通读实现来判定业务对错，硬做只会得到虚假的安心',
    '',
    '**三、留痕**',
    '- 任务书副本 + report.json + 测试输出 存 `<workspace>\\.claude-runs\\<task-id>\\`：由主代理转存，不要依赖 Claude Code 自己落盘。',
    '- 留痕是为了将来能查，不是为了现在占上下文：能脚本机械核对的就脚本化，不要把报告整段读回主上下文。',
    '',
    '## 六、什么时候别派',
    '',
    '- 业务规则本身还没定（连决策表都画不出）→ 先做最小一版再派。',
    '- 需要边做边改需求 → 结构上不适合（Claude Code 是异步一次性产出）。',
    '- 主代理手上已有全部上下文、改动只有几行 → 自己做，写任务书比干活贵。',
    '- 强依赖 DSH 会话历史或 DSH 生态（subagent / workflow / goal / todo）的任务 → 自己做。',
    '',
    '## 七、插件维护（改 dsh-claude-delegate 本身）',
    '- 改完源码：`npm run build`（同时产出 `lib/index.js` 与 `lib/client.js`）再 `npm run typecheck`。',
    '- 本地部署：把 `lib/` 覆盖到 profile 的 `node_modules/dsh-claude-delegate/`，然后**重启 dsh**；客户端半边改动必须重启，Web 端没有硬刷新。',
    '- 其他用户安装：`dsh plugin add dsh-claude-delegate`（npm 包带 bundle manifest，自动接线）。',
  ].join('\n'),
}
